---
apiVersion: v1
kind: Secret
metadata:
  name: mgmt-api-credentials
type: Opaque
data:
  management_url: {{ .Values.ibox.base64ManagementUrl }}
  username: {{ .Values.ibox.base64UserName }}
  password: {{ .Values.ibox.base64Password }}
