---
proxy:
  secretToken: d8dce5448115f9a196fb811b83693992ff055f1f451d85a417418cb7415b1f23
  service:
    nodePorts:
      http: 32222

singleuser:
  storage:
    # type: none
    dynamic:
      storageClass: ibox-iscsi-jupyterhub
    capacity: 40Gi
  lifecycleHooks:
    postStart:
      exec:
        #- command: ["gitpuller", "https://git.infinidat.com/dohlemacher/notebooks.git", "master", "demos/notebooks"]
        command: ["gitpuller", "https://git.infinidat.com/dohlemacher/infinidat-k8s-installer.git", "PSDEV-235/AddHelmChart", "demos/infinidat-k8s-installer"]

hub:
  db:
    type: sqlite-pvc
    pvc:
      storageClassName: ibox-iscsi-jupyterhub

iscsi:
  enable: true
  fsType: ext4
  readonly: false
  networkspaces: iscsi1
  poolName: "ps-k8s-jupyter"
  provisionType: "THIN"
  ssd_enabled: true
  noRootSquash: true
provisioner:
  image: "docker.io/infinidat/infinidat-k8s-provisioner" # Join
  imageTag: "latest"
  logLevel: "-v=9"

# CN=infinidat,OU=Security Groups,OU=Groups,OU=Corp,DC=infinidat,DC=com
### LDAP/AD Configuration
auth:
  type: ldap
  ldap:
    server:
      address: 'infinidat.com'
    dn:
      lookup: true 
      search:
        filter: '({login_attr}={login})'
      templates:
        - 'CN={username},ou=Professional Services USA,ou=Infinidat Global,ou=Users,ou=Corp,dc=infinidat,dc=com'
      user:
        searchBase: 'ou=Professional Services USA,ou=Infinidat Global,ou=Users,ou=Corp,dc=infinidat,dc=com'
        escape: False 
        attribute: 'sAMAccountName'
        dnAttribute: 'cn'
    allowedGroups:
      - 'cn=US Professional Services,ou=Non team dls,ou=Groups,ou=Corp,dc=infinidat,dc=com'
  state:
    enabled: false
  admin:
    access: true
    users:
      - dohlemacher
      - jnichols
      - kfred 

### Dummy auth working with a common password
# auth:
#   type: dummy
#   whitelist:
#     users:
#       - dohlemacher
#       - kfred
#       - jnichols
#       - gtouretsky
#   admin:
#     access: true
#     users:
#       - dohlemacher
#   dummy:
#     password: xsignnet1
#   ldap:
#     dn:
#       search: {}
#       user: {}
#     user: {}
#   state:
#     enabled: false
#     cryptoKey:
